name: data_application_layer
description: This package manages the communication between remote and local resources and the domain layer.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  # Network client
  retrofit: ^3.0.1+1
  dio: ^4.0.4
  # Database
  drift: ^1.4.0
  sqlite3_flutter_libs: ^0.5.3
  path_provider: ^2.0.9
  path: ^1.8.1
  # Serialization / Deserialization
  json_annotation: ^4.4.0
  fpdart: ^0.0.14
  get_it: ^7.2.0
  injectable: ^1.5.3

dev_dependencies:
  flutter_lints: ^1.0.4
  dependency_validator: ^3.1.2
  build_runner: ^2.1.7
  drift_dev: ^1.4.0
  json_serializable: ^6.1.4
  injectable_generator: ^1.5.3

flutter: