name: data_application_layer
description: This package manages the communication between remote and local resources and the domain layer.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  # Network client
  retrofit: ^4.0.1
  dio: ^5.0.3
  web_socket_channel: ^2.1.0
  http: ^0.13.4
  # Database
  drift: ^2.6.0
  sqlite3_flutter_libs: ^0.5.3
  path_provider: ^2.0.9
  path: ^1.8.0
  # Serialization / Deserialization
  json_annotation: ^4.8.0
  fpdart: ^0.5.0
  get_it: ^7.2.0
  injectable: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.1
  dependency_validator: ^3.1.2
  build_runner: ^2.1.7
  drift_dev: ^2.6.0
  json_serializable: ^6.6.1
  injectable_generator: ^2.1.4
  retrofit_generator: ^6.0.0+1

flutter: